### ISSUE TITLE
Why we set  `n<=65536` in `paramgen_from_seed` fn？

### ISSUE THREAD

**Issue by 3for** [algorand/pointproofs#16]
Could you tell me the reason to set  `n<=65536=2^16` in `paramgen_from_seed` fn？

In the Scalar field:
r=52435875175126190479447740508185965837690552500527637822603658699938581184513
factor(r)=2^32*t

For public parameter: g1^{alpha},....,g1^{alpha^(2n)}，
why not set `n<=2^31` instead of `n<=2^16`？

**Comment by reyzin** [comment]
paramgen_from_seed is a placeholder for testing. That's not how paramgen will actually be done, because it needs to be done by a trusted party. The real paramgen will determine the actual n. The check if n<=65536 is just a sanity check because you probably won't want a bigger n for performance reasons. The specific choice of 65536 is arbitrary and can be changed.
